name: 'dz_case_study'
version: '1.0.0'
config-version: 2
profile: 'dz_case_study'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  dz_case_study:
    staging:
      +materialized: view
    dwh:
      +materialized: table
    marts:
      +materialized: table

seeds:
  dz_case_study:
    +delimiter: ";"
    kunden:
      +column_types:
        changedate: varchar
        eroeffnungsdatum: varchar
        vrb_filial_und_betreuernr_an964: varchar
        kunde_id: varchar
    bestaende:
      +column_types:
        datum: varchar
        kunde_id: varchar
    mittelfluesse:
      +column_types:
        datum: varchar
        kunde_id: varchar
